name: flutter_ai_toolkit_example
description: >-
  Sample apps showing off various features of the Flutter AI Toolkit.
publish_to: none

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: '>=3.29.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_ai_toolkit:
    path: ..
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.3
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_app_check: ^0.3.2-4
  firebase_vertexai: ^1.0.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  go_router: ^14.2.8
  uuid: ^4.5.1
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_markdown: ^0.7.4+1
  google_fonts: ^6.2.1
  future_builder_ex: ^5.0.0
  split_view: ^3.2.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipes_default.json
    - assets/halloween-bg.png
